import { useEffect, useMemo, useState } from "react";
import { browserLocalPersistence, onAuthStateChanged, setPersistence, signInWithEmailAndPassword, signOut, User } from "firebase/auth";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc, writeBatch } from "firebase/firestore";
import { Image, LogOut, Pencil, Plus, Search, ShoppingBag, Trash2, X } from "lucide-react";
import { auth, db } from "./firebase";
import { catalogSeed } from "./catalogSeed";

type Product = {
  id: string;
  name: string;
  price: number;
  description: string;
  category: string;
  image: string;
  options: string;
  active: boolean;
};

type FormState = Omit<Product, "id">;
const categories = ["Combos", "Tradicionais", "Especiais", "Baguetes & hot dog", "Pastéis", "Panquecas & espaguetes", "Porções & bebidas"];
const emptyForm: FormState = { name: "", price: 0, description: "", category: "Combos", image: "", options: "", active: true };

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { await setPersistence(auth, browserLocalPersistence); const result = await signInWithEmailAndPassword(auth, email, password); onLogin(result.user); } catch { setError("E-mail ou senha inválidos. Ative o login por e-mail no Firebase."); } finally { setLoading(false); } };
  return <main className="login-page"><div className="login-card"><div className="brand-mark"><ShoppingBag size={22} /></div><p className="kicker">PAINEL DE CONTROLE</p><h1>Lanchão Massa</h1><p className="muted">Entre para gerenciar produtos, preços e fotos do cardápio.</p><form onSubmit={submit}><label>E-mail<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="admin@lanchao.com" /></label><label>Senha<input type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={loading}>{loading ? "Entrando..." : "Entrar no painel"}</button></form></div></main>;
}

function ProductModal({ product, onClose, onSave }: { product: Product | null; onClose: () => void; onSave: (data: FormState) => Promise<void> }) {
  const [form, setForm] = useState<FormState>(product ? { ...product } : emptyForm); const [saving, setSaving] = useState(false);
  const set = (key: keyof FormState, value: string | number | boolean) => setForm(current => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); await onSave(form); setSaving(false); };
  return <div className="modal-backdrop"><section className="modal"><header><div><p className="kicker">{product ? "EDITAR PRODUTO" : "NOVO PRODUTO"}</p><h2>{product ? product.name : "Adicionar ao cardápio"}</h2></div><button className="icon" onClick={onClose} aria-label="Fechar"><X size={19} /></button></header><form onSubmit={submit} className="product-form"><div className="form-grid"><label>Nome do produto<input required value={form.name} onChange={e => set("name", e.target.value)} placeholder="Ex.: X-Tudo" /></label><label>Preço<input required min="0" step="0.01" type="number" value={form.price || ""} onChange={e => set("price", Number(e.target.value))} placeholder="0,00" /></label></div><label>Categoria<select value={form.category} onChange={e => set("category", e.target.value)}>{categories.map(category => <option key={category}>{category}</option>)}</select></label><label>Descrição<textarea required value={form.description} onChange={e => set("description", e.target.value)} placeholder="Ingredientes e detalhes do produto" rows={3} /></label><label>Link da foto<input type="url" value={form.image} onChange={e => set("image", e.target.value)} placeholder="https://.../foto-do-produto.jpg" /><small>Cole aqui o link público da imagem. O cardápio usa essa URL automaticamente.</small></label><label>Opções <span className="muted">(opcional)</span><input value={form.options} onChange={e => set("options", e.target.value)} placeholder="Ex.: Carne, Frango, Calabresa" /><small>Separe as opções por vírgula.</small></label><label className="switch-row"><input type="checkbox" checked={form.active} onChange={e => set("active", e.target.checked)} /> Produto disponível no cardápio</label><footer><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving ? "Salvando..." : "Salvar produto"}</button></footer></form></section></div>;
}

function Dashboard({ user }: { user: User }) {
  const [products, setProducts] = useState<Product[]>([]); const [search, setSearch] = useState(""); const [modal, setModal] = useState<Product | "new" | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { const unsub = onSnapshot(query(collection(db, "products"), orderBy("name")), snapshot => setProducts(snapshot.docs.map(item => { const data = item.data() as Record<string, unknown>; return { id: item.id, name: String(data.name ?? ""), price: Number(data.price ?? 0), description: String(data.description ?? ""), category: String(data.category ?? categories[0]), image: String(data.image ?? ""), options: Array.isArray(data.options) ? data.options.join(", ") : String(data.options ?? ""), active: data.active !== false }; }))); return unsub; }, []);
  const visible = useMemo(() => products.filter(product => product.name.toLowerCase().includes(search.toLowerCase()) || product.category.toLowerCase().includes(search.toLowerCase())), [products, search]);
  const save = async (data: FormState) => { if (modal === "new") await addDoc(collection(db, "products"), { ...data, options: data.options.split(",").map(item => item.trim()).filter(Boolean), createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); else if (modal) await updateDoc(doc(db, "products", modal.id), { ...data, options: data.options.split(",").map(item => item.trim()).filter(Boolean), updatedAt: serverTimestamp() }); setModal(null); setNotice("Produto salvo. O cardápio público será atualizado automaticamente."); setTimeout(() => setNotice(""), 3500); };
  const remove = async (product: Product) => { if (!window.confirm(`Remover “${product.name}” do cardápio?`)) return; await deleteDoc(doc(db, "products", product.id)); setNotice("Produto removido."); setTimeout(() => setNotice(""), 3000); };
  const importCurrentCatalog = async () => { const batch = writeBatch(db); catalogSeed.forEach((item) => batch.set(doc(collection(db, "products")), { ...item, createdAt: serverTimestamp(), updatedAt: serverTimestamp() })); await batch.commit(); setNotice("Cardápio atual importado. Agora você pode editar cada produto."); };
  return <div className="admin-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><ShoppingBag size={19} /></span><span><b>Lanchão</b><em>Massa admin</em></span></div><div className="side-note"><strong>Cardápio conectado</strong><span>As alterações no Firebase aparecem no site público sem editar código.</span></div><button className="logout" onClick={() => signOut(auth)}><LogOut size={16} /> Sair</button></aside><main className="admin-main"><header className="admin-header"><div><p className="kicker">GERENCIAMENTO</p><h1>Produtos do cardápio</h1><p className="muted">Adicione, edite preços, descrições e links das fotos.</p></div><div className="admin-user">{user.email}<button className="primary" onClick={() => setModal("new")}><Plus size={17} /> Novo produto</button></div></header>{notice && <div className="notice">{notice}</div>}<div className="toolbar"><div className="search"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar produtos..." /></div><span>{products.length} produtos cadastrados</span></div>{products.length === 0 ? <section className="empty"><ShoppingBag size={34} /><h2>Seu cardápio começa aqui</h2><p>Cadastre manualmente ou importe os produtos que já estão no site.</p><div className="empty-actions"><button className="primary" onClick={() => setModal("new")}><Plus size={17} /> Adicionar produto</button><button className="secondary" onClick={importCurrentCatalog}>Importar cardápio atual</button></div></section> : <section className="product-table"><div className="table-head"><span>Produto</span><span>Categoria</span><span>Preço</span><span>Status</span><span /></div>{visible.map(product => <article className="product-row" key={product.id}><div className="product-info">{product.image ? <img src={product.image} alt="" /> : <div className="image-placeholder"><Image size={18} /></div>}<div><strong>{product.name}</strong><small>{product.description}</small></div></div><span className="category-chip">{product.category}</span><strong>R$ {product.price.toFixed(2).replace(".", ",")}</strong><span className={product.active ? "status active" : "status inactive"}>{product.active ? "Ativo" : "Oculto"}</span><div className="row-actions"><button className="icon" onClick={() => setModal(product)} aria-label="Editar"><Pencil size={16} /></button><button className="icon danger" onClick={() => remove(product)} aria-label="Remover"><Trash2 size={16} /></button></div></article>)}</section>}{modal && <ProductModal product={modal === "new" ? null : modal} onClose={() => setModal(null)} onSave={save} />}</main></div>;
}

export default function App() { const [user, setUser] = useState<User | null>(null); useEffect(() => onAuthStateChanged(auth, setUser), []); return user ? <Dashboard user={user} /> : <Login onLogin={setUser} />; }
