import { useEffect, useMemo, useState } from "react";
import { browserLocalPersistence, onAuthStateChanged, setPersistence, signInWithEmailAndPassword, signOut, User } from "firebase/auth";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, writeBatch } from "firebase/firestore";
import { Image, LogOut, Palette, Pencil, Plus, Search, ShoppingBag, Trash2, X } from "lucide-react";
import { auth, db } from "./firebase";
import { catalogSeed } from "./catalogSeed";

type Product = {
  id: string;
  name: string;
  price: number;
  description: string;
  category: string;
  image: string;
  options: string;
  active: boolean;
};

type FormState = Omit<Product, "id">;
const categories = ["Combos", "Tradicionais", "Especiais", "Baguetes & hot dog", "Pastéis", "Panquecas & espaguetes", "Porções & bebidas"];
const emptyForm: FormState = { name: "", price: 0, description: "", category: "Combos", image: "", options: "", active: true };
type StoreSettings = { name: string; color: string; logo: string };
const defaultStoreSettings: StoreSettings = { name: "Lanchão Massa", color: "#ee5b28", logo: "/logo-lanchao-massa.png" };
const IMGBB_API_KEY = import.meta.env.VITE_IMGBB_API_KEY as string | undefined;

const handleImageError = (event: React.SyntheticEvent<HTMLImageElement>) => {
  const image = event.currentTarget;
  if (image.dataset.fallbackApplied) return;
  image.dataset.fallbackApplied = "true";
  image.src = "/logo-lanchao-massa.png";
};

async function uploadImageToImgBB(file: File): Promise<string> {
  if (!IMGBB_API_KEY) throw new Error("A chave do ImgBB ainda não foi configurada na Vercel.");
  if (file.size > 32 * 1024 * 1024) throw new Error("A imagem precisa ter no máximo 32 MB.");
  const body = new FormData();
  body.append("key", IMGBB_API_KEY);
  body.append("image", file);
  const response = await fetch("https://api.imgbb.com/1/upload", { method: "POST", body });
  const result = await response.json() as { success?: boolean; data?: { url?: string }; error?: { message?: string } };
  if (!response.ok || !result.success || !result.data?.url) throw new Error(result.error?.message || "Não foi possível enviar a imagem.");
  return result.data.url;
}

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { await setPersistence(auth, browserLocalPersistence); const result = await signInWithEmailAndPassword(auth, email, password); onLogin(result.user); } catch { setError("E-mail ou senha inválidos. Ative o login por e-mail no Firebase."); } finally { setLoading(false); } };
  return <main className="login-page"><div className="login-card"><div className="brand-mark"><ShoppingBag size={22} /></div><p className="kicker">PAINEL DE CONTROLE</p><h1>ADMINISTRAÇÃO</h1><p className="muted">Entre para gerenciar produtos, preços e fotos do cardápio.</p><form onSubmit={submit}><label>E-mail<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="admin@lanchao.com" /></label><label>Senha<input type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={loading}>{loading ? "Entrando..." : "Entrar no painel"}</button></form></div></main>;
}

function ProductModal({ product, onClose, onSave }: { product: Product | null; onClose: () => void; onSave: (data: FormState) => Promise<void> }) {
  const [form, setForm] = useState<FormState>(product ? { ...product } : emptyForm);
  const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState("");
  const set = (key: keyof FormState, value: string | number | boolean) => setForm(current => ({ ...current, [key]: value }));
  const handleFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploadError(""); setUploading(true); try { set("image", await uploadImageToImgBB(file)); } catch (error) { setUploadError(error instanceof Error ? error.message : "Falha ao enviar a foto."); } finally { setUploading(false); event.target.value = ""; } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await onSave(form); } finally { setSaving(false); } };
  return <div className="modal-backdrop"><section className="modal"><header><div><p className="kicker">{product ? "EDITAR PRODUTO" : "NOVO PRODUTO"}</p><h2>{product ? product.name : "Adicionar ao cardápio"}</h2></div><button className="icon" onClick={onClose} aria-label="Fechar"><X size={19} /></button></header><form onSubmit={submit} className="product-form"><div className="form-grid"><label>Nome do produto<input required value={form.name} onChange={e => set("name", e.target.value)} placeholder="Ex.: X-Tudo" /></label><label>Preço<input required min="0" step="0.01" type="number" value={form.price || ""} onChange={e => set("price", Number(e.target.value))} placeholder="0,00" /></label></div><label>Categoria<select value={form.category} onChange={e => set("category", e.target.value)}>{categories.map(category => <option key={category}>{category}</option>)}</select></label><label>Descrição<textarea required value={form.description} onChange={e => set("description", e.target.value)} placeholder="Ingredientes e detalhes do produto" rows={3} /></label><div className="image-upload"><label>Foto do produto<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={handleFile} disabled={uploading} /><small>{uploading ? "Enviando foto e gerando link..." : "Escolha uma imagem: o link será gerado automaticamente."}</small></label>{form.image && <img className="image-preview" src={form.image} alt="Pré-visualização do produto" onError={handleImageError} />}{uploadError && <p className="error">{uploadError}</p>}<label>Link da foto<input type="url" value={form.image} onChange={e => set("image", e.target.value)} placeholder="https://.../foto-do-produto.jpg" /><small>Você também pode colar um link direto manualmente.</small></label></div><label>Opções <span className="muted">(opcional)</span><input value={form.options} onChange={e => set("options", e.target.value)} placeholder="Ex.: Carne, Frango, Calabresa" /><small>Separe as opções por vírgula.</small></label><label className="switch-row"><input type="checkbox" checked={form.active} onChange={e => set("active", e.target.checked)} /> Produto disponível no cardápio</label><footer><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving || uploading}>{uploading ? "Enviando foto..." : saving ? "Salvando..." : "Salvar produto"}</button></footer></form></section></div>;
}

function StoreSettingsModal({ settings, onClose, onSave }: { settings: StoreSettings; onClose: () => void; onSave: (settings: StoreSettings) => Promise<void> }) {
  const [form, setForm] = useState(settings); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState("");
  const handleLogo = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploadError(""); setUploading(true); try { const logo = await uploadImageToImgBB(file); setForm(current => ({ ...current, logo })); } catch (error) { setUploadError(error instanceof Error ? error.message : "Falha ao enviar a logo."); } finally { setUploading(false); event.target.value = ""; } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await onSave(form); } finally { setSaving(false); } };
  return <div className="modal-backdrop"><section className="modal settings-modal"><header><div><p className="kicker">IDENTIDADE DA LOJA</p><h2>Configurações do site</h2></div><button className="icon" onClick={onClose} aria-label="Fechar"><X size={19} /></button></header><form onSubmit={submit} className="product-form"><label>Nome da loja<input required maxLength={45} value={form.name} onChange={e => setForm(current => ({ ...current, name: e.target.value }))} placeholder="Ex.: Lanchão Massa" /><small>Esse nome aparece no cardápio e nas mensagens do WhatsApp.</small></label><label>Cor principal<div className="color-control"><input type="color" value={form.color} onChange={e => setForm(current => ({ ...current, color: e.target.value }))} /><input value={form.color} onChange={e => setForm(current => ({ ...current, color: e.target.value }))} placeholder="#ee5b28" /></div><small>Use a cor da marca em botões e destaques do site.</small></label><div className="image-upload settings-logo-upload"><label>Logo do site<input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleLogo} disabled={uploading} /><small>{uploading ? "Enviando logo e gerando link..." : "Envie uma imagem ou cole um link direto."}</small></label>{form.logo && <img className="image-preview" src={form.logo} alt="Prévia da logo" onError={handleImageError} />}<label>Link da logo<input type="url" value={form.logo} onChange={e => setForm(current => ({ ...current, logo: e.target.value }))} placeholder="https://.../logo.png" /></label>{uploadError && <p className="error">{uploadError}</p>}</div><div className="settings-preview" style={{ borderColor: form.color }}><span style={{ background: form.color }} /> Prévia da identidade da loja</div><footer><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" style={{ background: form.color }} disabled={saving || uploading}>{uploading ? "Enviando logo..." : saving ? "Salvando..." : "Salvar configurações"}</button></footer></form></section></div>;
}

function Dashboard({ user }: { user: User }) {
  const [products, setProducts] = useState<Product[]>([]); const [search, setSearch] = useState(""); const [modal, setModal] = useState<Product | "new" | null>(null); const [settingsOpen, setSettingsOpen] = useState(false); const [settings, setSettings] = useState<StoreSettings>(defaultStoreSettings); const [notice, setNotice] = useState("");
  useEffect(() => { const unsub = onSnapshot(query(collection(db, "products"), orderBy("name")), snapshot => setProducts(snapshot.docs.map(item => { const data = item.data() as Record<string, unknown>; return { id: item.id, name: String(data.name ?? ""), price: Number(data.price ?? 0), description: String(data.description ?? ""), category: String(data.category ?? categories[0]), image: String(data.image ?? ""), options: Array.isArray(data.options) ? data.options.join(", ") : String(data.options ?? ""), active: data.active !== false }; }))); return unsub; }, []);
  useEffect(() => onSnapshot(doc(db, "settings", "store"), snapshot => { const data = snapshot.data() as Partial<StoreSettings> | undefined; if (data) setSettings({ name: String(data.name || defaultStoreSettings.name), color: String(data.color || defaultStoreSettings.color), logo: String(data.logo || defaultStoreSettings.logo) }); }), []);
  const visible = useMemo(() => products.filter(product => product.name.toLowerCase().includes(search.toLowerCase()) || product.category.toLowerCase().includes(search.toLowerCase())), [products, search]);
  const save = async (data: FormState) => { if (modal === "new") await addDoc(collection(db, "products"), { ...data, options: data.options.split(",").map(item => item.trim()).filter(Boolean), createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); else if (modal) await updateDoc(doc(db, "products", modal.id), { ...data, options: data.options.split(",").map(item => item.trim()).filter(Boolean), updatedAt: serverTimestamp() }); setModal(null); setNotice("Produto salvo. O cardápio público será atualizado automaticamente."); setTimeout(() => setNotice(""), 3500); };
  const remove = async (product: Product) => { if (!window.confirm(`Remover “${product.name}” do cardápio?`)) return; await deleteDoc(doc(db, "products", product.id)); setNotice("Produto removido."); setTimeout(() => setNotice(""), 3000); };
  const importCurrentCatalog = async () => { const batch = writeBatch(db); catalogSeed.forEach((item) => batch.set(doc(collection(db, "products")), { ...item, createdAt: serverTimestamp(), updatedAt: serverTimestamp() })); await batch.commit(); setNotice("Cardápio atual importado. Agora você pode editar cada produto."); };
  const saveSettings = async (next: StoreSettings) => { await setDoc(doc(db, "settings", "store"), { ...next, updatedAt: serverTimestamp() }); setSettings(next); setSettingsOpen(false); setNotice("Identidade da loja atualizada. O site público será atualizado automaticamente."); setTimeout(() => setNotice(""), 4000); };
  return <div className="admin-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><ShoppingBag size={19} /></span><span><b>ADMINISTRAÇÃO</b><em>painel</em></span></div><button className="settings-button" onClick={() => setSettingsOpen(true)}><Palette size={16} /> Configurar loja</button><div className="side-note"><strong>Cardápio conectado</strong><span>As alterações no Firebase aparecem no site público sem editar código.</span></div><button className="logout" onClick={() => signOut(auth)}><LogOut size={16} /> Sair</button></aside><main className="admin-main"><header className="admin-header"><div><p className="kicker">GERENCIAMENTO</p><h1>Produtos do cardápio</h1><p className="muted">Adicione, edite preços, descrições e links das fotos.</p></div><div className="admin-user">{user.email}<button className="primary" onClick={() => setModal("new")}><Plus size={17} /> Novo produto</button></div></header>{notice && <div className="notice">{notice}</div>}<div className="toolbar"><div className="search"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar produtos..." /></div><span>{products.length} produtos cadastrados</span></div>{products.length === 0 ? <section className="empty"><ShoppingBag size={34} /><h2>Seu cardápio começa aqui</h2><p>Cadastre manualmente ou importe os produtos que já estão no site.</p><div className="empty-actions"><button className="primary" onClick={() => setModal("new")}><Plus size={17} /> Adicionar produto</button><button className="secondary" onClick={importCurrentCatalog}>Importar cardápio atual</button></div></section> : <section className="product-table"><div className="table-head"><span>Produto</span><span>Categoria</span><span>Preço</span><span>Status</span><span /></div>{visible.map(product => <article className="product-row" key={product.id}><div className="product-info">{product.image ? <img src={product.image} alt="" onError={handleImageError} /> : <div className="image-placeholder"><Image size={18} /></div>}<div><strong>{product.name}</strong><small>{product.description}</small></div></div><span className="category-chip">{product.category}</span><strong>R$ {product.price.toFixed(2).replace(".", ",")}</strong><span className={product.active ? "status active" : "status inactive"}>{product.active ? "Ativo" : "Oculto"}</span><div className="row-actions"><button className="icon" onClick={() => setModal(product)} aria-label="Editar"><Pencil size={16} /></button><button className="icon danger" onClick={() => remove(product)} aria-label="Remover"><Trash2 size={16} /></button></div></article>)}</section>}{modal && <ProductModal product={modal === "new" ? null : modal} onClose={() => setModal(null)} onSave={save} />}{settingsOpen && <StoreSettingsModal settings={settings} onClose={() => setSettingsOpen(false)} onSave={saveSettings} />}</main></div>;
}

export default function App() { const [user, setUser] = useState<User | null>(null); useEffect(() => onAuthStateChanged(auth, setUser), []); return user ? <Dashboard user={user} /> : <Login onLogin={setUser} />; }
